# Documentation: https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
  - update
  - build
  - test

image: python:3.6

before_script:
  - apt-get install -qy graphviz

update apt:
  stage: update
  only:
    - dev
    - merge_requests
  before_script:
    - apt-get update -qy

build protos:
  stage: build
  only:
    - dev
    - merge_requests
  script:
    - pip install pipenv
    - pipenv install -d --system --deploy
    - make protos

code lint:
  stage: test
  allow_failure: yes
  only:
    - dev
    - merge_requests
  script:
    - make check

unit tests:
  stage: test
  only:
    - dev
    - web
  script:
    - make tests
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
