# Documentation: https://docs.gitlab.com/ce/ci/yaml/README.html

stages:
  - linters
  - unit-tests

check:
  stage: linters
  image: python:3.6
  allow_failure: yes
  before_script:
    # install pipenv and generate dev-requirements.txt (stdout) from Pipfile.lock on the fly
    - pip install pipenv
    - pip install -r <(pipenv lock -rd)
    # dev requirements installed directly by pip, do not prefix with `pipenv run`
    # protobuf files should be generated because they improve mypy checks
    - make protos
  script:
    - make check

unit-tests:
  stage: unit-tests
  image: python:3.6
  before_script:
    - apt update
    - apt install -y graphviz
    - apt install -y librocksdb-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev
    - pip install pipenv
    - pipenv sync -d
    - pipenv run pip install python-rocksdb==0.7.0
    - pipenv run make protos
  script:
    - pipenv run make tests
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
